/**
 * The FLEET DISPATCH MANIFEST CONSUMER, decision half. Phase 21, FF-B379.
 *
 * `src/claude-orchestration.cts` emits a dispatch manifest under the kind
 * `FLEET_MANIFEST_KIND`. Until this module existed nothing read that manifest, so
 * every path that resolved the fleet backend printed a line saying the consumer
 * was not built and executed inline. This module is the half of the consumer that
 * DECIDES, and `scripts/fleet-dispatch.cjs` is the half that dispatches.
 *
 * THIS MODULE IMPORTS NOTHING, for the same reason `src/fleet-manager.cts`
 * imports nothing: every input arrives as an argument, so a battery over it varies
 * everything the answer can depend on. It spawns nothing, reads no file and holds
 * no clock.
 *
 * ─── THE EXPECTED KIND IS AN ARGUMENT, NEVER A LITERAL ───────────────────────
 *
 * The kind this consumer accepts is supplied by the caller, which reads it off the
 * PRODUCER's own export. A transcribed copy of `ferrox.fleet.dispatch/v1` here
 * would keep accepting manifests after the producer changed the kind, which is a
 * consumer reporting that it consumed something it did not understand. The same
 * argument is already made at `src/claude-orchestration.cts:786` about why the
 * kind is exported at all. An ABSENT expected kind is therefore a refusal in its
 * own right rather than a wildcard: a comparison against nothing accepts
 * everything, and this repository has shipped that exact defect once already.
 *
 * ─── OVERLAPPING WRITE LANES NEVER DISPATCH ──────────────────────────────────
 *
 * A stage is a set of plans the fleet runs AT THE SAME TIME. Two plans in one
 * stage that both declare the same file are 2 worker processes editing 1 file, and
 * the partition in `partitionStages` exists precisely to make that impossible. So
 * this module RE VERIFIES the invariant rather than trusting it. The manifest
 * arrives from a file, and a file can be edited, generated by an older emitter, or
 * assembled by hand. A consumer that trusted the producer's promise would dispatch
 * the collision the promise was supposed to prevent, and it would do it silently.
 *
 * ─── THE FLEET CLAIM IS A FUNCTION OF INTEGERS, NEVER OF A FLAG ──────────────
 *
 * `classifyDispatch` decides whether a run may be described as a fleet run, and it
 * decides it from OBSERVED COUNTS. A boolean saying "dispatched" is satisfied by an
 * implementation that reports a dispatch and spawns nothing, and a run that spawned
 * 1 worker is a sequential run whatever it is called. Both are the defect this
 * whole project exists to prevent, so the claim is derived from counters and the
 * counters are asserted before any property over them.
 *
 * ─── A TOTAL IS NOT A WIDTH, AND ONLY THE WIDTH IS A FLEET ───────────────────
 *
 * A spawn TOTAL cannot tell a fleet from a queue. A run at capacity 1 over 3 nodes
 * spawns 3 workers and never runs 2 at once, and a classification reading only the
 * total would report that sequential run as a fleet. So the claim additionally
 * requires DEMONSTRATED WIDTH: the largest number of worker intervals observed
 * OPEN AT THE SAME TIME, which `foldRunRecord` computes from closed intervals in
 * the run log and which never rounds up. `DISPATCHED_SEQUENTIALLY` is the outcome
 * for a run that spawned plenty and overlapped nothing, and it exists because that
 * run is the most convincing false fleet a person can be shown.
 *
 * ADR-457 build-at-publish: this TS source compiles to the artifact
 * ferrox-core/bin/lib/fleet-dispatch-plan.cjs, which is TRACKED and committed. CJS
 * module shape (`export =`). The module owns NO stdout. Never throws.
 */

// ─── Refusal codes ────────────────────────────────────────────────────────────

/**
 * Every way a manifest can fail to become a dispatch plan, frozen. Callers branch
 * on a code and never on prose.
 */
const FLEET_DISPATCH_ERROR_CODES = Object.freeze({
  /** The caller supplied no kind to compare against, so nothing can be verified. */
  E_DISPATCH_NO_EXPECTED_KIND: 'E_DISPATCH_NO_EXPECTED_KIND',
  /** No manifest reached the consumer at all. */
  E_DISPATCH_MANIFEST_ABSENT: 'E_DISPATCH_MANIFEST_ABSENT',
  /** Something arrived that is not a manifest shaped object. */
  E_DISPATCH_MANIFEST_MALFORMED: 'E_DISPATCH_MANIFEST_MALFORMED',
  /** A manifest of some other kind, or of no kind. */
  E_DISPATCH_KIND_MISMATCH: 'E_DISPATCH_KIND_MISMATCH',
  /** A manifest that describes no work. */
  E_DISPATCH_NO_WAVES: 'E_DISPATCH_NO_WAVES',
  /** A wave that is not a wave. */
  E_DISPATCH_BAD_WAVE: 'E_DISPATCH_BAD_WAVE',
  /** A stage that is not a stage. */
  E_DISPATCH_BAD_STAGE: 'E_DISPATCH_BAD_STAGE',
  /** A plan that is not a plan. */
  E_DISPATCH_BAD_PLAN: 'E_DISPATCH_BAD_PLAN',
  /** One node id in 2 places, so 1 node would be dispatched twice. */
  E_DISPATCH_DUPLICATE_NODE: 'E_DISPATCH_DUPLICATE_NODE',
  /** Two plans in 1 stage declaring 1 file: 2 workers editing 1 file. */
  E_DISPATCH_OVERLAPPING_LANES: 'E_DISPATCH_OVERLAPPING_LANES',
  /** A capacity ceiling that is not a positive whole number. */
  E_DISPATCH_BAD_CAPACITY_CAP: 'E_DISPATCH_BAD_CAPACITY_CAP',
});

/**
 * The outcome vocabulary. One frozen set, so the line a person reads, the field a
 * caller branches on and the value a test asserts are all 1 string.
 */
const DISPATCH_OUTCOMES = Object.freeze({
  /** The manifest never became a plan. Nothing was dispatched. */
  MANIFEST_REFUSED: 'manifest_refused',
  /** The plan named nodes the work graph does not carry. */
  GRAPH_MISMATCH: 'graph_mismatch',
  /** The fleet preconditions refused. No worker was spawned. */
  PREFLIGHT_REFUSED: 'preflight_refused',
  /** The driver failed before or while dispatching. */
  DRIVER_FAILED: 'driver_failed',
  /** Dispatch was attempted and no worker process was ever observed. */
  DISPATCHED_NOTHING: 'dispatched_nothing',
  /** Exactly 1 worker was observed. That is a sequential run, not a fleet run. */
  DISPATCHED_SINGLE_WORKER: 'dispatched_single_worker',
  /** Many workers, never 2 at once. A queue with a fleet's spawn total. */
  DISPATCHED_SEQUENTIALLY: 'dispatched_sequentially',
  /** More than 1 worker was observed at the same time, on more than 1 node. */
  DISPATCHED_FLEET: 'dispatched_fleet',
});

/**
 * The smallest number of observed worker spawns that may be described as a fleet.
 *
 * Stated once, as a named constant, because it is the entire difference between a
 * fleet run and a sequential run wearing the word fleet.
 */
const FLEET_MINIMUM_WORKERS = 2;

/**
 * The smallest DEMONSTRATED WIDTH that may be described as a fleet.
 *
 * Equal to `FLEET_MINIMUM_WORKERS` today and named separately anyway, because the
 * 2 answer different questions: one bounds how many workers a run started, the
 * other bounds how many ran AT THE SAME TIME. Collapsing them into 1 constant is
 * how a sequential run starts passing for a fleet the day either bound moves.
 */
const FLEET_MINIMUM_WIDTH = 2;

// ─── Types ────────────────────────────────────────────────────────────────────

interface PlanEntry {
  id: string;
  brief: string;
  files_modified: string[];
}

interface StageEntry {
  index: number;
  plans: PlanEntry[];
  node_ids: string[];
}

interface WaveEntry {
  id: string;
  stages: StageEntry[];
}

interface PlanCounters {
  waves: number;
  stages: number;
  nodes: number;
  widest_stage: number;
  capacity: number;
  lane_conflicts: number;
  refusals: number;
  unwrapped: number;
}

interface DispatchPlan {
  phase_dir: string;
  run_id: string;
  budget_tokens: number | null;
  waves: WaveEntry[];
  node_ids: string[];
  capacity: number;
}

interface PlanOk {
  ok: true;
  code: null;
  reason: null;
  detail: null;
  plan: DispatchPlan;
  counters: PlanCounters;
}

interface PlanErr {
  ok: false;
  code: string;
  reason: string;
  detail: string | null;
  plan: null;
  counters: PlanCounters;
}

type PlanResult = PlanOk | PlanErr;

interface ReadInput {
  manifest?: unknown;
  expectedKind?: unknown;
  capacityCap?: unknown;
}

interface ClassifyInput {
  /** Did the fleet preconditions allow dispatch. */
  dispatch_allowed?: unknown;
  /** How many worker processes were OBSERVED starting. */
  observed_spawns?: unknown;
  /** How many DISTINCT nodes those spawns covered. */
  distinct_nodes?: unknown;
  /** The largest number of worker intervals observed open AT THE SAME TIME. */
  demonstrated_width?: unknown;
  /** Was that width folded from closed intervals only. Reported, never a gate. */
  width_exact?: unknown;
  /** A driver level failure, named. */
  error?: unknown;
}

interface DispatchVerdict {
  outcome: string;
  /** True only when this run may be described as a fleet run. */
  fleet: boolean;
  reason: string;
  counters: {
    observed_spawns: number;
    distinct_nodes: number;
    demonstrated_width: number;
    width_exact: boolean;
    minimum_workers: number;
    minimum_width: number;
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function zeroPlanCounters(): PlanCounters {
  return {
    waves: 0, stages: 0, nodes: 0, widest_stage: 0, capacity: 0,
    lane_conflicts: 0, refusals: 0, unwrapped: 0,
  };
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0;
}

/** A count as a non negative whole number, defaulting to 0. Never throws. */
function toCount(value: unknown): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) return 0;
  return value - (value % 1);
}

function refuse(counters: PlanCounters, code: string, reason: string, detail?: string): PlanErr {
  counters.refusals += 1;
  return { ok: false, code, reason, detail: detail === undefined ? null : detail, plan: null, counters };
}

/**
 * The manifest inside whatever the caller handed over.
 *
 * `ferrox-tools claude-orchestration emit-workflow --backend fleet` prints
 * `{ manifest, summary }`, so the thing on disk is usually an ENVELOPE rather than
 * the manifest itself. Accepting both is interoperability with the shipped
 * producer, not leniency: a consumer that only accepted the inner object would
 * refuse the exact bytes the emitter writes. The unwrap is COUNTED so a caller can
 * see which shape it was handed rather than having to guess.
 */
function unwrapManifest(value: unknown, counters: PlanCounters): unknown {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return value;
  const record = value as Record<string, unknown>;
  if (record['kind'] !== undefined) return value;
  const inner = record['manifest'];
  if (inner !== null && typeof inner === 'object' && !Array.isArray(inner)) {
    counters.unwrapped += 1;
    return inner;
  }
  return value;
}

// ─── The reader ───────────────────────────────────────────────────────────────

/**
 * Turn a dispatch manifest into a DISPATCH PLAN, or refuse by name.
 *
 * The order is fixed and every step refuses before the next one runs, so a
 * manifest that fails 2 ways is reported on the FIRST one and a caller reading a
 * code never has to guess which defect it names:
 *
 *   1. an expected kind must have been supplied
 *   2. a manifest must be present and object shaped
 *   3. the kind must match, exactly
 *   4. the waves, stages and plans must be well formed
 *   5. no node id may appear twice in the whole manifest
 *   6. no 2 plans in 1 stage may declare the same file
 *   7. the capacity ceiling, when given, must be a positive whole number
 *
 * Pure over its argument. Never throws.
 */
function readDispatchPlan(input: ReadInput | null | undefined): PlanResult {
  const counters = zeroPlanCounters();
  const source = (input === null || input === undefined || typeof input !== 'object') ? {} : input;

  const expectedKind = source.expectedKind;
  if (!isNonEmptyString(expectedKind)) {
    return refuse(
      counters,
      FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_NO_EXPECTED_KIND,
      'no expected manifest kind was supplied, so nothing could be verified. The kind is read '
      + 'off the producer\'s own export rather than transcribed here, and a comparison against '
      + 'nothing accepts everything',
    );
  }

  const manifest = unwrapManifest(source.manifest, counters);
  if (manifest === null || manifest === undefined) {
    return refuse(
      counters,
      FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_MANIFEST_ABSENT,
      'no dispatch manifest reached the consumer, so there is nothing to dispatch',
    );
  }
  if (typeof manifest !== 'object' || Array.isArray(manifest)) {
    return refuse(
      counters,
      FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_MANIFEST_MALFORMED,
      'the dispatch manifest is not an object, so it describes no waves and no plans',
      'received ' + (Array.isArray(manifest) ? 'an array' : 'a ' + typeof manifest),
    );
  }

  const record = manifest as Record<string, unknown>;
  if (record['kind'] !== expectedKind) {
    return refuse(
      counters,
      FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_KIND_MISMATCH,
      'the manifest kind is not the kind this consumer reads, so dispatching it would be '
      + 'acting on a document nobody has understood',
      'expected ' + JSON.stringify(expectedKind) + ', read ' + JSON.stringify(record['kind'] ?? null),
    );
  }

  const wavesRaw = record['waves'];
  if (!Array.isArray(wavesRaw) || wavesRaw.length === 0) {
    return refuse(
      counters,
      FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_NO_WAVES,
      'the manifest carries no waves, so it describes no work to dispatch',
    );
  }

  const seenNodes = new Set<string>();
  const waves: WaveEntry[] = [];
  const nodeIds: string[] = [];

  for (let wi = 0; wi < wavesRaw.length; wi += 1) {
    // Annotated `unknown` rather than inferred. `Array.isArray` narrows to `any[]`,
    // so an inferred element would be `any` and every shape test below it would be
    // decorative: a manifest is a file this module does not trust.
    const waveRaw: unknown = wavesRaw[wi];
    if (waveRaw === null || typeof waveRaw !== 'object' || Array.isArray(waveRaw)) {
      return refuse(
        counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_WAVE,
        'waves[' + wi + '] is not a wave object',
      );
    }
    const wave = waveRaw as Record<string, unknown>;
    if (!isNonEmptyString(wave['id'])) {
      return refuse(
        counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_WAVE,
        'waves[' + wi + '] has no id, so no run record could name which wave dispatched',
      );
    }
    const stagesRaw = wave['stages'];
    if (!Array.isArray(stagesRaw) || stagesRaw.length === 0) {
      return refuse(
        counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_WAVE,
        'waves[' + wi + '] carries no stages, so the wave describes no work',
      );
    }

    const stages: StageEntry[] = [];
    for (let si = 0; si < stagesRaw.length; si += 1) {
      const stageRaw: unknown = stagesRaw[si];
      if (stageRaw === null || typeof stageRaw !== 'object' || Array.isArray(stageRaw)) {
        return refuse(
          counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_STAGE,
          'waves[' + wi + '].stages[' + si + '] is not a stage object',
        );
      }
      const stage = stageRaw as Record<string, unknown>;
      const plansRaw = stage['plans'];
      if (!Array.isArray(plansRaw) || plansRaw.length === 0) {
        return refuse(
          counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_STAGE,
          'waves[' + wi + '].stages[' + si + '] carries no plans, so the stage dispatches nothing',
        );
      }

      const plans: PlanEntry[] = [];
      // The write lanes already claimed IN THIS STAGE, mapped to the plan that
      // claimed each one, so a refusal can name BOTH plans and the file rather
      // than only reporting that a collision exists somewhere.
      const laneOwner = new Map<string, string>();

      for (let pi = 0; pi < plansRaw.length; pi += 1) {
        const planRaw: unknown = plansRaw[pi];
        const where = 'waves[' + wi + '].stages[' + si + '].plans[' + pi + ']';
        if (planRaw === null || typeof planRaw !== 'object' || Array.isArray(planRaw)) {
          return refuse(
            counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_PLAN,
            where + ' is not a plan object',
          );
        }
        const plan = planRaw as Record<string, unknown>;
        if (!isNonEmptyString(plan['id'])) {
          return refuse(
            counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_PLAN,
            where + ' has no id, so no worker could be dispatched onto a named node',
          );
        }
        const id = plan['id'];
        if (typeof plan['brief'] !== 'string') {
          return refuse(
            counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_PLAN,
            where + ' (' + id + ') has no brief',
          );
        }
        const filesRaw = plan['files_modified'];
        if (!Array.isArray(filesRaw)) {
          return refuse(
            counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_PLAN,
            where + ' (' + id + ') declares no files_modified list. An UNDECLARED write lane '
            + 'cannot be checked for overlap, so it is refused rather than assumed empty',
          );
        }
        const files: string[] = [];
        for (const file of filesRaw) {
          if (!isNonEmptyString(file)) {
            return refuse(
              counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_PLAN,
              where + ' (' + id + ') has a files_modified entry that is not a non empty string',
            );
          }
          files.push(file);
        }

        if (seenNodes.has(id)) {
          return refuse(
            counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_DUPLICATE_NODE,
            'node ' + JSON.stringify(id) + ' appears more than once in the manifest, so 1 node '
            + 'would be dispatched twice in 1 run',
          );
        }
        seenNodes.add(id);

        // THE OVERLAP CHECK. Counted first, so a caller can see that the check
        // ran and found nothing rather than inferring it from the absence of a
        // refusal.
        for (const file of files) {
          const owner = laneOwner.get(file);
          if (owner !== undefined) {
            counters.lane_conflicts += 1;
            return refuse(
              counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_OVERLAPPING_LANES,
              'plans ' + JSON.stringify(owner) + ' and ' + JSON.stringify(id) + ' both declare '
              + JSON.stringify(file) + ' and share stage ' + si + ' of wave '
              + JSON.stringify(wave['id']) + '. A stage runs at the same time, so dispatching it '
              + 'would put 2 worker processes on 1 file',
              file,
            );
          }
          laneOwner.set(file, id);
        }

        plans.push({ id, brief: plan['brief'], files_modified: files });
        nodeIds.push(id);
      }

      const indexRaw = stage['index'];
      stages.push({
        index: typeof indexRaw === 'number' && Number.isFinite(indexRaw) ? indexRaw : si,
        plans,
        node_ids: plans.map((p) => p.id),
      });
      counters.stages += 1;
      if (plans.length > counters.widest_stage) counters.widest_stage = plans.length;
    }

    waves.push({ id: wave['id'], stages });
    counters.waves += 1;
  }

  counters.nodes = nodeIds.length;

  // ── The capacity, which is a property of the manifest and not a preference. ──
  //
  // The widest stage is how many plans the manifest itself says may run at the
  // same time. A ceiling BELOW it is a legitimate instruction from a caller with a
  // smaller machine; a ceiling above it would dispatch nothing extra, because no
  // stage has that many plans in it.
  const capRaw = source.capacityCap;
  let capacity = counters.widest_stage;
  if (capRaw !== undefined && capRaw !== null) {
    const cap = toCount(capRaw);
    if (cap === 0 || cap !== Number(capRaw)) {
      return refuse(
        counters, FLEET_DISPATCH_ERROR_CODES.E_DISPATCH_BAD_CAPACITY_CAP,
        'the capacity ceiling must be a positive whole number, and it was '
        + JSON.stringify(capRaw) + '. A silently coerced ceiling would make the run record '
        + 'describe a fleet nobody asked for',
      );
    }
    if (cap < capacity) capacity = cap;
  }
  counters.capacity = capacity;

  const budgetRaw = (manifest as Record<string, unknown>)['budgetTokens'];
  const phaseDirRaw = (manifest as Record<string, unknown>)['phaseDir'];
  const runIdRaw = (manifest as Record<string, unknown>)['runId'];

  return {
    ok: true,
    code: null,
    reason: null,
    detail: null,
    plan: {
      phase_dir: isNonEmptyString(phaseDirRaw) ? phaseDirRaw : '',
      run_id: isNonEmptyString(runIdRaw) ? runIdRaw : '',
      budget_tokens: typeof budgetRaw === 'number' && Number.isFinite(budgetRaw) ? budgetRaw : null,
      waves,
      node_ids: nodeIds,
      capacity,
    },
    counters,
  };
}

// ─── The honesty verdict ──────────────────────────────────────────────────────

/**
 * Decide what this run may be CALLED, from what was observed.
 *
 * The rules, in this order:
 *
 *   1. a named driver error is a driver failure, whatever else was observed
 *   2. a refused preflight is a refusal, and it can never be a fleet run
 *   3. 0 observed spawns is `dispatched_nothing`
 *   4. fewer than `FLEET_MINIMUM_WORKERS` spawns, or spawns covering fewer than
 *      `FLEET_MINIMUM_WORKERS` distinct nodes, is a SINGLE WORKER run
 *   5. a demonstrated width below `FLEET_MINIMUM_WIDTH` is a SEQUENTIAL run
 *   6. anything else is a fleet run
 *
 * Rule 4 tests BOTH counters on purpose. Two spawns on 1 node are 2 sequential
 * attempts at the same work, which is a retry and not a fan out, and a
 * classification that read only the spawn total would report a retrying
 * sequential run as a fleet.
 *
 * Rule 5 is what makes the word fleet mean anything. Rules 3 and 4 are satisfied
 * by a run at capacity 1 over 3 nodes, which starts 3 workers, finishes each
 * before starting the next, and is a queue. The width is folded from CLOSED worker
 * intervals and never rounds up, so a width at or above the floor is a fact about
 * processes that were alive together and not an inference about how many were
 * asked for.
 *
 * `width_exact` is REPORTED and is deliberately not a gate. An inexact width is a
 * LOWER bound, so a width of 2 that is inexact still witnesses 2 concurrent
 * workers; refusing the claim on inexactness would deny a fact that was observed.
 * A width below the floor is refused whether exact or not, which is the direction
 * that cannot overstate.
 *
 * Pure. Never throws.
 */
function classifyDispatch(input: ClassifyInput | null | undefined): DispatchVerdict {
  const source = (input === null || input === undefined || typeof input !== 'object') ? {} : input;
  const spawns = toCount(source.observed_spawns);
  const nodes = toCount(source.distinct_nodes);
  const width = toCount(source.demonstrated_width);
  const counters = {
    observed_spawns: spawns,
    distinct_nodes: nodes,
    demonstrated_width: width,
    width_exact: source.width_exact === true,
    minimum_workers: FLEET_MINIMUM_WORKERS,
    minimum_width: FLEET_MINIMUM_WIDTH,
  };

  if (isNonEmptyString(source.error)) {
    return {
      outcome: DISPATCH_OUTCOMES.DRIVER_FAILED,
      fleet: false,
      reason: 'the fleet driver failed: ' + source.error,
      counters,
    };
  }

  if (source.dispatch_allowed !== true) {
    return {
      outcome: DISPATCH_OUTCOMES.PREFLIGHT_REFUSED,
      fleet: false,
      reason: 'the fleet preconditions refused, so no worker was spawned and this run executed '
        + 'nothing as a fleet',
      counters,
    };
  }

  if (spawns === 0) {
    return {
      outcome: DISPATCH_OUTCOMES.DISPATCHED_NOTHING,
      fleet: false,
      reason: 'dispatch was allowed and 0 worker processes were observed starting, so nothing '
        + 'ran as a fleet',
      counters,
    };
  }

  if (spawns < FLEET_MINIMUM_WORKERS || nodes < FLEET_MINIMUM_WORKERS) {
    return {
      outcome: DISPATCH_OUTCOMES.DISPATCHED_SINGLE_WORKER,
      fleet: false,
      reason: spawns + ' worker process(es) were observed across ' + nodes + ' node(s). A run '
        + 'that did not put at least ' + FLEET_MINIMUM_WORKERS + ' workers on at least '
        + FLEET_MINIMUM_WORKERS + ' nodes is a sequential run and is not reported as a fleet run',
      counters,
    };
  }

  if (width < FLEET_MINIMUM_WIDTH) {
    return {
      outcome: DISPATCH_OUTCOMES.DISPATCHED_SEQUENTIALLY,
      fleet: false,
      reason: spawns + ' worker process(es) were observed across ' + nodes + ' node(s) and never '
        + 'more than ' + width + ' at the same time. A run that started many workers and '
        + 'overlapped fewer than ' + FLEET_MINIMUM_WIDTH + ' of them is a queue, and a spawn '
        + 'total is not a width',
      counters,
    };
  }

  return {
    outcome: DISPATCH_OUTCOMES.DISPATCHED_FLEET,
    fleet: true,
    reason: spawns + ' worker processes were observed across ' + nodes + ' nodes, and '
      + width + ' of them ran at the same time',
    counters,
  };
}

/**
 * The 1 line a person reads. Every outcome names the count it was decided from,
 * so a reader never has to take the word for the number.
 */
function formatDispatchLine(verdict: DispatchVerdict | null | undefined): string {
  if (verdict === null || verdict === undefined || typeof verdict !== 'object') {
    return 'fleet dispatch: unknown (no verdict)';
  }
  const counters = (verdict.counters !== null && typeof verdict.counters === 'object')
    ? verdict.counters
    : {
      observed_spawns: 0, distinct_nodes: 0, demonstrated_width: 0, width_exact: false,
      minimum_workers: FLEET_MINIMUM_WORKERS, minimum_width: FLEET_MINIMUM_WIDTH,
    };
  return 'fleet dispatch: ' + String(verdict.outcome)
    + ' | fleet run: ' + (verdict.fleet === true ? 'yes' : 'no')
    + ' | workers observed: ' + String(counters.observed_spawns)
    + ' | nodes: ' + String(counters.distinct_nodes)
    + ' | concurrent width: ' + String(counters.demonstrated_width)
    + ' | ' + String(verdict.reason);
}

export = {
  FLEET_DISPATCH_ERROR_CODES,
  DISPATCH_OUTCOMES,
  FLEET_MINIMUM_WORKERS,
  FLEET_MINIMUM_WIDTH,
  readDispatchPlan,
  classifyDispatch,
  formatDispatchLine,
};
